---
- hosts: all
  gather_facts: yes
  roles:
  - role: ccdc.vagrant-base-box
    # For the Windows 10 and 11 images this needs to be
    # commented out. Vagrant cannot import Hyper-V base boxes
    # with more than one drive connected, so for the test
    # boxes *only* we're provisioning a single large drive
    # instead of three smaller ones.
    # This is a known issue logged with Hashicorp at
    # https://github.com/hashicorp/vagrant/issues/10831.
    vars:
      drive_configuration:
        - letter: d
          label: x_mirror
          number: 1
          online: true
          readonly: false
        - letter: e
          label: builds
          number: 2
          online: true
          readonly: false
  - role: ccdc.install-vm-tools
  - role: ccdc.debloat-windows
    vars:
      disable_telemetry_dnsblock: false
  - role: ccdc.compact-vm-image
